### ISSUE TITLE
Cannot install on Windows 10 x64

### ISSUE THREAD

**Issue by gmask** [winnfsd/vagrant-winnfsd#114]
Hello, this is a fresh install of Vagrant 1.9.8, I receive the following error:

```
$ vagrant plugin install vagrant-winnfsd
Installing the 'vagrant-winnfsd' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies rb-inotify (= 0.9.10) and rb-inotify (= 0.9.8)
  Activated rb-inotify-0.9.8
  which does not match conflicting dependency (= 0.9.10)

  Conflicting dependency chains:
    rb-inotify (= 0.9.8), 0.9.8 activated

  versus:
    rb-inotify (= 0.9.10)

  Gems matching rb-inotify (= 0.9.10):
    rb-inotify-0.9.10
```

Any idea how to fix?

**Comment by jamesmacwhite** [comment]
I believe this an upstream issue with Vagrant itself. Have a look at the workaround here and see if helps:

https://github.com/mitchellh/vagrant/issues/8785

**Comment by gmask** [comment]
Thanks, the following command did work:
`$ VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1 vagrant plugin install vagrant-winnfsd`

What I don't understand is why a complete uninstall of Vagrant did not solve this issue.

**Comment by faysal-abridge** [comment]
Hi, getting the following error on my windows 10 pc
```
vagrant plugin install vagrant-vbguest
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies multi_json (= 1.12.1) and multi_json (= 1.12.2)
  Activated multi_json-1.12.2
  which does not match conflicting dependency (= 1.12.1)

  Conflicting dependency chains:
    multi_json (= 1.12.2), 1.12.2 activated

  versus:
    multi_json (= 1.12.1)

  Gems matching multi_json (= 1.12.1):
    multi_json-1.12.1
```
Any workaround or quick fix on windows?

**Comment by Arbagen** [comment]
@faysal-abridge did you resolved it?

**Comment by devamitbera** [comment]
Getting  below error on 

```

C:/xampp/hostvagrant/ubuntuspace/Vagrantfile:5:in `block in <top (required)>': vagrant-vbguest plugin is not installed!  Please run the following command: vagrant plugin install vagrant-vbguest (RuntimeError)
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/config/v2/loader.rb:37:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/config/loader.rb:126:in `block (2 levels) in load'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/config/loader.rb:119:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/config/loader.rb:119:in `block in load'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/config/loader.rb:116:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/config/loader.rb:116:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/vagrantfile.rb:28:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:777:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:777:in `vagrantfile'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:523:in `host'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:191:in `block in action_runner'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:33:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:510:in `hook'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:759:in `unload'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:164:in `ensure in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:164:in `<main>'



```

**VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1** is not resolved
