### ISSUE TITLE
Permission denied @ rb_sysopen

### ISSUE THREAD

**Issue by Pushkraj19** [winnfsd/vagrant-winnfsd#144]
Hello,

I am having issues when installing plugin.

I tried in it powershell as well as in cmd prompt with admin and regular prompt. but i get permission error:

```
K:\Homestead>vagrant plugin install vagrant-winnfsd
Installing the 'vagrant-winnfsd' plugin. This can take a few minutes...
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/package.rb:448:in `initialize': Permission denied @ rb_sysopen - C:/Users/Administrator/.vagrant.d/gems/3.1.3/gems/vagrant-winnfsd-1.4.0/bin/winnfsd.exe (Errno::EACCES)
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/package.rb:448:in `open'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/package.rb:448:in `block (2 levels) in extract_tar_gz'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/package/tar_reader.rb:65:in `each'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/package.rb:415:in `block in extract_tar_gz'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/package.rb:541:in `block in open_tar_gz'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/package.rb:538:in `wrap'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/package.rb:538:in `open_tar_gz'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/package.rb:414:in `extract_tar_gz'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/package.rb:392:in `block (2 levels) in extract_files'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/package/tar_reader.rb:65:in `each'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/package.rb:389:in `block in extract_files'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/package/file_source.rb:29:in `open'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/package/file_source.rb:29:in `with_read_io'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/package.rb:386:in `extract_files'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/installer.rb:852:in `extract_files'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/installer.rb:324:in `install'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/resolver/specification.rb:104:in `install'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/request_set.rb:279:in `block in install_into'        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/request_set.rb:271:in `each'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/request_set.rb:271:in `install_into'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/bundler.rb:611:in `internal_install'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/bundler.rb:355:in `install'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/plugin/manager.rb:138:in `block in install_plugin'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/plugin/manager.rb:148:in `install_plugin'        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/plugins/commands/plugin/action/install_gem.rb:30:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/action/warden.rb:48:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/action/builder.rb:180:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/action/runner.rb:101:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/action/runner.rb:101:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/plugins/commands/plugin/command/base.rb:14:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/plugins/commands/plugin/command/install.rb:70:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/plugins/commands/plugin/command/install.rb:69:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/plugins/commands/plugin/command/install.rb:69:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/plugins/commands/plugin/command/root.rb:66:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/cli.rb:67:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/lib/vagrant/environment.rb:301:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.7/bin/vagrant:248:in `<main>'
```

**Comment by Pushkraj19** [comment]
Update:

deleted all versions from C:/Users/Administrator/.vagrant.d/gems/ and restarted pc. then reinstalled and it fixed the issue.
